name: Go Release
on:
  push:
    branches:
      - main
    paths:
      - 'go/**'
env:
  BUCKET_NAME : "sym-releases"
  AWS_REGION : "us-east-1"
permissions:
      id-token: write
      contents: read    # This is required for actions/checkout@v2
jobs:
  GoPackageUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.15.0'
      - name: Build handler package
        run: |
          make
        working-directory: go
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::746659639185:role/GitHubReleaseBucketAccess
          role-session-name: GitHubActions-${{ github.run_id }}-${{ github.run_number }}
          aws-region: ${{ env.AWS_REGION }}
      - name:  Copy package to s3
        run: |
          aws s3 cp --acl authenticated-read ./go/dist/handler.zip s3://${{ env.BUCKET_NAME }}/lambda-templates/go.zip
