name: Typescript Release
on:
  push:
    branches:
      - main
    paths:
      - 'typescript/**'
env:
  BUCKET_NAME : "sym-releases"
  AWS_REGION : "us-east-1"
permissions:
      id-token: write
      contents: read    # This is required for actions/checkout@v2
jobs:
  NodePackageUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Build handler package
        run: |
          build.sh
        working-directory: typescript
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::746659639185:role/GitHubReleaseBucketAccess
          role-session-name: GitHubActions-${{ github.run_id }}-${{ github.run_number }}
          aws-region: ${{ env.AWS_REGION }}
      - name:  Copy package to s3
        run: |
          aws s3 cp --acl authenticated-read ./typescript/handler.zip s3://${{ env.BUCKET_NAME }}/lambda-templates/typescript.zip
